/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'gsus' at '04/09/15 17.09' with Gradle 2.6
 *
 * @author gsus, @date 04/09/15 17.09
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
